# Generated by Django 5.0.6 on 2024-07-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamenBernarpostApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
    ]
