# Generated by Django 5.0.6 on 2024-07-05 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamenBernarpostApp', '0003_rename_post_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='image_url',
        ),
    ]
