# Generated by Django 5.0.6 on 2024-07-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamenBernarpostApp', '0004_remove_posts_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='posts',
            name='username',
            field=models.TextField(max_length=100),
        ),
    ]
