# Generated by Django 5.0.6 on 2024-07-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamenBernarpostApp', '0006_posts_created_at_posts_image_url_alter_posts_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
