# Generated by Django 5.0.6 on 2024-07-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamenBernarpostApp', '0007_planes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planes',
            name='codigo',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='planes',
            name='email',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
